# Generated by Django 4.0.6 on 2023-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('email_id', models.CharField(max_length=50, null=True)),
                ('phoneno', models.CharField(max_length=50, null=True)),
                ('packages', models.CharField(max_length=50, null=True)),
                ('Date', models.CharField(max_length=50, null=True)),
                ('Messages', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
